cicd consiquenses

diff --git a/.github/workflows/time_peace.yml b/.github/workflows/time_peace.yml
--- a/.github/workflows/time_peace.yml
+++ b/.github/workflows/time_peace.yml
@@ -29,19 +29,19 @@ jobs:
       run: go test -v ./...
 
   deploy:
-        runs-on: ubuntu-latest
+    runs-on: ubuntu-latest
     
-        steps:
-        - name: Checkout Repository
-          uses: actions/checkout@v2
-    
-        - name: Set up SSH
-          run: |
-            mkdir -p ~/.ssh
-            echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
-            chmod 600 ~/.ssh/id_rsa
-            ssh-keyscan -t rsa ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
-    
-        - name: Deploy to AWS EC2
-          run: |
-            ssh -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} 'cd TIME_PEACE && git pull && ./deploy.sh'
+   
+    steps:
+    - name: Deploy to AWS EC2
+      uses: appleboy/ssh-action@master
+      with:
+        host: ${{secrets.EC2_PUBLIC_IP}}
+        username: ubuntu
+        key: ${{secrets.EC2_SSH_KEY}}
+        script: |
+          echo "Connected to AWS EC2 instance"
+          cd TIME_PEACE
+          git pull  || { echo "Failed to pull"; exit 1; }
+          go build -o build/bin ./cmd/api
+           systemctl restart myapp.service || { echo "Failed to restart service"; exit 1; }
